---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: swiss-army-knife
  name: swiss-army-knife
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: swiss-army-knife
  namespace: kube-system
  labels:
    app: swiss-army-knife
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: swiss-army-knife
  name: swiss-army-knife
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: swiss-army-knife
subjects:
- kind: ServiceAccount
  name: swiss-army-knife
  namespace: kube-system
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: swiss-army-knife
  namespace: kube-system
  labels:
    app: swiss-army-knife
spec:
  allowPrivilegeEscalation: true
  allowedCapabilities:
  - '*'
  fsGroup:
    rule: RunAsAny
  hostIPC: true
  hostNetwork: true
  hostPID: true
  hostPorts:
  - max: 65535
    min: 0
  privileged: true
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: swiss-army-knife
  name: swiss-army-knife-psp
  namespace: kube-system
rules:
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  resourceNames:
  - swiss-army-knife
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: swiss-army-knife-psp-binding
  labels:
    app: swiss-army-knife
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: swiss-army-knife-psp
subjects:
- kind: ServiceAccount
  name: swiss-army-knife
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: swiss-army-knife
  namespace: kube-system
  labels:
    app: swiss-army-knife
spec:
  selector:
    matchLabels:
      name: swiss-army-knife
  template:
    metadata:
      labels:
        name: swiss-army-knife
    spec:
      tolerations:
      - operator: Exists
      containers:
      - name: swiss-army-knife
        image: supporttools/swiss-army-knife
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true        
        resources:
          limits:
            cpu: 1000m
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName            
        volumeMounts:
        - name: rootfs
          mountPath: /rootfs
      serviceAccountName: swiss-army-knife         
      volumes:
      - name: rootfs
        hostPath:
          path: /