---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: alt-etcd-s3-sync
  name: etcd-s3
  namespace: kube-system
type: Opaque
data:
  # all values should be base64 encoded (ie: echo -n '123456' | base64)
  S3_ACCESS_KEY:
  S3_BUCKET_NAME:
  S3_BUCKET_REGION:
  S3_ENDPOINT:
  S3_FOLDER:
  S3_SECRET_KEY:
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    app: alt-etcd-s3-sync
  name: alt-etcd-s3-sync
  namespace: kube-system
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: beta.kubernetes.io/os
                    operator: NotIn
                    values:
                    - windows
                  - key: node-role.kubernetes.io/etcd
                    operator: In
                    values:
                    - "true"
          containers:
          - args:
            - /opt/rke-tools/rke-etcd-backup
            - etcd-backup
            - save
            - --cacert
            - /etc/kubernetes/ssl/kube-ca.pem
            - --cert
            - /etc/kubernetes/ssl/kube-node.pem
            - --key
            - /etc/kubernetes/ssl/kube-node-key.pem
            - --s3-backup=true
            - --name
            - etcd-rolling-snapshots
            - --creation=12h
            - --retention=72h
            - --once
            envFrom:
            - secretRef:
                name: etcd-s3
                optional: false
            image: rancher/rke-tools:v0.1.66
            name: alt-etcd-s3-sync
            volumeMounts:
            - mountPath: /backup
              name: rke-tools
            - mountPath: /etc/kubernetes
              name: certs
              readOnly: true
          hostNetwork: true
          restartPolicy: Never
          tolerations:
          - effect: NoExecute
            key: node-role.kubernetes.io/etcd
            operator: Equal
            value: "true"          
          volumes:
          - hostPath:
              path: /opt/rke/etcd-snapshots
              type: ""
            name: rke-tools
          - hostPath:
              path: /etc/kubernetes
              type: ""
            name: certs
  schedule: '0 */12 * * *'
  successfulJobsHistoryLimit: 3
