---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: unset-nodeid
  namespace: longhorn-system
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: unset-nodeid
rules:
  - apiGroups: [""]
    resources: ["volumes.longhorn.io"]
    verbs: ["list", "watch", "get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
 name: unset-nodeid
 namespace: longhorn-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: unset-nodeid
subjects:
- kind: ServiceAccount
  name: unset-nodeid
  namespace: longhorn-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: unset-nodeid
  name: unset-nodeid
  namespace: unset-nodeid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unset-nodeid
  template:
    metadata:
      labels:
        app: unset-nodeid
    spec:
      serviceAccount: unset-nodeid
      serviceAccountName: unset-nodeid
      containers:
      - args:
        - /root/bin/longhorn_unset_node_id.sh
        env:
        - name: LOOP_SLEEP
          value: "60"
        - name: LONGHORN_NAMESPACE
          value: "longhorns-system"
        - name: AlertOnly
          value: "False"
        image: rancherlabs/swiss-army-knife
        imagePullPolicy: IfNotPresent
        name: unset-nodeid
        volumeMounts:
        - mountPath: /root/bin/
          name: unset-nodeid
      volumes:
      - configMap:
          defaultMode: 493
          items:
          - key: longhorn_unset_node_id.sh
            mode: 0755
            path: longhorn_unset_node_id.sh
          name: unset-nodeid
          optional: false
        name: unset-nodeid
